// ponytail: one-shot backfill — point existing meme rows at the scenic base-image
// pipeline (no people) and re-arm visual search. Safe to re-run: rows already in the
// scenic shape are only re-pended (idempotent-ish), batches/daily counters are
// regenerated by the feed.
//
//   bun src/scripts/backfill-meme-visuals.ts
import { eq } from "drizzle-orm";
import { db } from "../lib/db";
import { generatedContents, visualFeedDaily, visualSearchBatches } from "../db/schema";
import { buildMemeBackgroundQueries } from "../modules/visual/visual.queries";
import { memeScenicCategory } from "../modules/ugc/ugc.service";

const dedupe = (list: string[]): string[] => {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const item of list) {
    const key = item.trim().toLowerCase();
    if (!key || seen.has(key)) continue;
    seen.add(key);
    out.push(item.trim());
  }
  return out;
};

const rows = await db.select().from(generatedContents).where(eq(generatedContents.contentFormat, "meme"));
const now = new Date().toISOString();
let updated = 0;

for (const row of rows) {
  const jokeTags = (() => {
    try {
      const parsed = JSON.parse(String(row.visualTags ?? "[]"));
      return Array.isArray(parsed) ? parsed.map((t) => String(t)) : [];
    } catch {
      return [] as string[];
    }
  })();
  const scenicQueries = buildMemeBackgroundQueries({ visualTags: jokeTags, visualMood: row.emotion, contentFormat: "meme" }, 2);
  const scenicTags = dedupe(scenicQueries.map((q) => q.split(/\s+/).slice(0, 2).join(" ")));
  if (!scenicTags.length) continue;
  await db
    .update(generatedContents)
    .set({
      visualTags: JSON.stringify(scenicTags),
      visualStyle: "lifestyle",
      visualCategory: memeScenicCategory(scenicQueries[0] ?? ""),
      visualAssetId: null,
      visualSearchStatus: "pending",
      visualSearchError: null,
      updatedAt: now,
    } as any)
    .where(eq(generatedContents.id, row.id));
  updated++;
}

// batches are per-day bookkeeping — drop them so the worker re-processes the
// re-pended rows instead of skipping already-"ready" batches; daily counters reset too.
await db.delete(visualSearchBatches);
await db.delete(visualFeedDaily);

console.log(`backfill complete: ${updated}/${rows.length} meme rows re-armed for scenic visual search`);
